databases:
  - name: guitarstore
    databaseName: guitarstore_hokk
    user: guitarstore_hokk_user

services:
  - type: web
    name: guitar_store3
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: guitarstore
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false